name: Kwiki-UserName
version: 0.14
abstract: Kwiki User Name Plugin
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.37
  Kwiki::UserPreferences: 0.13
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
