name: Kwiki-UserName
version: 0.12
abstract: Kwiki User Name Plugin
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.32
  Kwiki::UserPreferences: 0.11
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
